apiVersion: 1

datasources:
  - name: airplanes
    type: postgres
    url: host.docker.internal:5432
    user: admin
    database: airplanes
    secureJsonData:
      password: 'admin'
    jsonData:
      database: airplanes
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1400 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false